In [1]:
import pandas as pd

In [2]:
# Load your dataset
df = pd.read_csv("Data/raw/IT Troubleshouting DATAset - Feuille 1.csv")
df

,problems,solutions
0,Forgotten Password,Go to the “Forgot Password” or “Reset Password...
1,Account Locked,"First, we need to verify your identity. This c..."
2,Lost Login Credentials,Start by attempting username recovery. Many sy...
3,Software Won’t Run,Check for software compatibility with the oper...
4,Application Errors,"Restart the application. Often, a simple r..."
...,...,...
96,Corrupted Windows profile,"Log in with admin account, rename corrupted pr..."
97,Database transaction log full (SQL Server / Or...,"Back up transaction logs, shrink log file if r..."
98,RAID array degraded,"Identify failed disk via RAID controller, repl..."
99,Linux server stuck in emergency mode at boot,"Boot into recovery mode, check /etc/fstab for ..."
100,Windows kernel power error,Indicates improper shutdown or hardware instab...

In [4]:
df.rename(columns={
    df.columns[0]: "Customer_Issue",
    df.columns[1]: "Tech_Response"
}, inplace=True)
df

,Customer_Issue,Tech_Response
0,Forgotten Password,Go to the “Forgot Password” or “Reset Password...
1,Account Locked,"First, we need to verify your identity. This c..."
2,Lost Login Credentials,Start by attempting username recovery. Many sy...
3,Software Won’t Run,Check for software compatibility with the oper...
4,Application Errors,"Restart the application. Often, a simple r..."
...,...,...
96,Corrupted Windows profile,"Log in with admin account, rename corrupted pr..."
97,Database transaction log full (SQL Server / Or...,"Back up transaction logs, shrink log file if r..."
98,RAID array degraded,"Identify failed disk via RAID controller, repl..."
99,Linux server stuck in emergency mode at boot,"Boot into recovery mode, check /etc/fstab for ..."
100,Windows kernel power error,Indicates improper shutdown or hardware instab...

In [5]:
# 1. Drop duplicate issues
df = df.drop_duplicates(subset="Customer_Issue", keep="first")
df

,Customer_Issue,Tech_Response
0,Forgotten Password,Go to the “Forgot Password” or “Reset Password...
1,Account Locked,"First, we need to verify your identity. This c..."
2,Lost Login Credentials,Start by attempting username recovery. Many sy...
3,Software Won’t Run,Check for software compatibility with the oper...
4,Application Errors,"Restart the application. Often, a simple r..."
...,...,...
96,Corrupted Windows profile,"Log in with admin account, rename corrupted pr..."
97,Database transaction log full (SQL Server / Or...,"Back up transaction logs, shrink log file if r..."
98,RAID array degraded,"Identify failed disk via RAID controller, repl..."
99,Linux server stuck in emergency mode at boot,"Boot into recovery mode, check /etc/fstab for ..."
100,Windows kernel power error,Indicates improper shutdown or hardware instab...

In [6]:
# Remove leading/trailing spaces in column names and values
df.columns = df.columns.str.strip()
df["Customer_Issue"] = df["Customer_Issue"].astype(str).str.strip()
df["Tech_Response"] = df["Tech_Response"].astype(str).str.strip()

In [7]:
# Drop rows where either column is missing
df.dropna(subset=["Customer_Issue", "Tech_Response"], inplace=True)

In [8]:
df.head(5)

           Customer_Issue                                      Tech_Response
0      Forgotten Password  Go to the “Forgot Password” or “Reset Password...
1          Account Locked  First, we need to verify your identity. This c...
2  Lost Login Credentials  Start by attempting username recovery. Many sy...
3      Software Won’t Run  Check for software compatibility with the oper...
4      Application Errors  Restart the application. Often, a simple resta...

In [9]:
df.tail()

,Customer_Issue,Tech_Response
96,Corrupted Windows profile,"Log in with admin account, rename corrupted pr..."
97,Database transaction log full (SQL Server / Or...,"Back up transaction logs, shrink log file if r..."
98,RAID array degraded,"Identify failed disk via RAID controller, repl..."
99,Linux server stuck in emergency mode at boot,"Boot into recovery mode, check /etc/fstab for ..."
100,Windows kernel power error,Indicates improper shutdown or hardware instab...

In [ ]:
# Save cleaned dataset
df.to_csv("Data/processed/IT_Troubleshooting_DATAset_ready.csv", index=False)